export type Elf = {
  id: string;
  name: string;
  gender: "boy" | "girl";
  emoji: string;
  accent: string; // tailwind gradient classes for avatar background
  bio: string;
  personality: string;
  hobbies: string[];
  job: string;
  treats: string[];
  funFact: string;
  signOff: string;
};
export const ELVES: Elf[] = [
  // ---------- BOY ELVES ----------
  {
    id: "jingle",
    name: "Jingle",
    gender: "boy",
    emoji: "🛷",
    accent: "from-red-500 to-rose-600",
    bio: "The fastest sledder in the whole North Pole! Jingle zooms down Peppermint Hill every morning before work.",
    personality: "Funny and full of energy",
    hobbies: ["Sledding", "Telling jokes", "Snowball tag"],
    job: "Toy Maker in Santa's Workshop",
    treats: ["Hot cocoa with extra marshmallows", "Gingerbread men"],
    funFact: "Once sledded so fast his hat flew all the way to the South Pole!",
    signOff: "Zoom zoom and candy canes",
  },
  {
    id: "tinsel-tom",
    name: "Tinsel Tom",
    gender: "boy",
    emoji: "🎄",
    accent: "from-emerald-500 to-green-700",
    bio: "Tom decorates every Christmas tree in Santa's village. He can hang 100 ornaments in one minute!",
    personality: "Cheerful and artistic",
    hobbies: ["Decorating trees", "Painting ornaments", "Ice skating"],
    job: "Chief Tree Decorator",
    treats: ["Sugar cookies shaped like stars", "Peppermint bark"],
    funFact: "His personal tree has 2,000 twinkling lights on it!",
    signOff: "Sparkles and tinsel",
  },
  {
    id: "cocoa",
    name: "Cocoa",
    gender: "boy",
    emoji: "☕",
    accent: "from-amber-600 to-orange-800",
    bio: "Cocoa runs the Hot Chocolate Station where every elf stops for a warm cup before work.",
    personality: "Warm, cozy and kind",
    hobbies: ["Inventing cocoa recipes", "Reading by the fire", "Snowman building"],
    job: "Head of the Hot Chocolate Station",
    treats: ["Triple-marshmallow cocoa", "Chocolate snowballs"],
    funFact: "He has invented 47 different flavors of hot chocolate!",
    signOff: "Warm hugs and marshmallows",
  },
  {
    id: "blitzen-buddy",
    name: "Buddy Blitz",
    gender: "boy",
    emoji: "🦌",
    accent: "from-orange-500 to-amber-700",
    bio: "Buddy trains the young reindeer to fly. Rudolph is his very best friend!",
    personality: "Brave and encouraging",
    hobbies: ["Reindeer flying lessons", "Star gazing", "Carrot farming"],
    job: "Reindeer Flight Trainer",
    treats: ["Carrot cake", "Cinnamon rolls"],
    funFact: "He once rode on Rudolph's back over the Northern Lights!",
    signOff: "Up up and away",
  },
  {
    id: "peppermint-pete",
    name: "Peppermint Pete",
    gender: "boy",
    emoji: "🍬",
    accent: "from-rose-400 to-red-600",
    bio: "Pete stripes every candy cane by hand in the Candy Cane Factory. Stripes are his specialty!",
    personality: "Silly and sweet",
    hobbies: ["Candy making", "Juggling candy canes", "Singing carols"],
    job: "Candy Cane Striper",
    treats: ["Peppermint sticks", "Candy cane ice cream"],
    funFact: "He once made a candy cane taller than Santa's house!",
    snoFF: "",
    signOff: "Stripes and sweetness",
  } as Elf,
  {
    id: "frosty-finn",
    name: "Frosty Finn",
    gender: "boy",
    emoji: "⛄",
    accent: "from-sky-400 to-blue-600",
    bio: "Finn is the North Pole's snowman-building champion three years in a row!",
    personality: "Playful and imaginative",
    hobbies: ["Snowman building", "Ice sculpting", "Snow angel contests"],
    job: "Snow Groundskeeper of Santa's Village",
    treats: ["Snow cones", "Vanilla frosted cookies"],
    funFact: "He built a snowman so tall it waved at airplanes!",
    signOff: "Snowflakes and smiles",
  },
  {
    id: "gadget",
    name: "Gadget",
    gender: "boy",
    emoji: "🔧",
    accent: "from-slate-500 to-slate-700",
    bio: "Gadget fixes every toy machine in the workshop. If it beeps, boops, or spins — Gadget built it!",
    personality: "Curious and clever",
    hobbies: ["Inventing machines", "Robot building", "Puzzle solving"],
    job: "Workshop Machine Engineer",
    treats: ["Gear-shaped gingerbread", "Fizzy snowberry juice"],
    funFact: "He built a robot that wraps 1,000 presents an hour!",
    signOff: "Beeps, boops and jingle bells",
  },
  {
    id: "carol-max",
    name: "Melody Max",
    gender: "boy",
    emoji: "🎵",
    accent: "from-violet-500 to-purple-700",
    bio: "Max leads the Elf Choir and writes brand-new Christmas songs every single week.",
    personality: "Musical and joyful",
    hobbies: ["Singing carols", "Playing jingle bells", "Whistling with birds"],
    job: "Director of the North Pole Choir",
    treats: ["Musical note macarons", "Caroling cocoa"],
    funFact: "He can sing 'Jingle Bells' in 12 different languages!",
    signOff: "Fa la la la la",
  },
  {
    id: "scout",
    name: "Scout Snowfield",
    gender: "boy",
    emoji: "🧭",
    accent: "from-teal-500 to-cyan-700",
    bio: "Scout maps Santa's sleigh route around the whole world every Christmas Eve.",
    personality: "Adventurous and wise",
    hobbies: ["Exploring glaciers", "Map drawing", "Penguin spotting"],
    job: "Chief Sleigh Route Navigator",
    treats: ["Explorer trail mix", "Iceberg lemonade"],
    funFact: "He has visited every country in the world with Santa!",
    signOff: "Adventure awaits",
  },
  {
    id: "twinkle-toes",
    name: "Twinkle Toes",
    gender: "boy",
    emoji: "✨",
    accent: "from-yellow-400 to-amber-600",
    bio: "The lightest-footed elf ever! He tiptoes into houses to sprinkle Christmas magic dust.",
    personality: "Gentle and magical",
    hobbies: ["Tip-toe dancing", "Magic dust collecting", "Hide and seek"],
    job: "Christmas Magic Sprinkler",
    treats: ["Stardust sprinkle donuts", "Golden honey cookies"],
    funFact: "He is so quiet, even the mice can't hear him!",
    signOff: "Twinkles and stardust",
  },
  // ---------- GIRL ELVES ----------
  {
    id: "holly",
    name: "Holly",
    gender: "girl",
    emoji: "🍪",
    accent: "from-red-400 to-rose-600",
    bio: "Holly bakes cookies for every elf in the village and feeds the reindeer their breakfast every morning.",
    personality: "Sweet and caring",
    hobbies: ["Baking cookies", "Feeding reindeer", "Knitting tiny scarves"],
    job: "Reindeer Feeder & Head Baker",
    treats: ["Warm chocolate chip cookies", "Reindeer-shaped brownies"],
    funFact: "Comet the reindeer only eats carrots if Holly sings to him first!",
    signOff: "Cookies and cuddles",
  },
  {
    id: "ivy",
    name: "Ivy Evergreen",
    gender: "girl",
    emoji: "🌟",
    accent: "from-green-400 to-emerald-600",
    bio: "Ivy places the star on top of every tree in the North Pole — she rides a flying ladder to reach!",
    personality: "Confident and kind",
    hobbies: ["Star polishing", "Flying ladder rides", "Wreath weaving"],
    job: "Official Star Placer",
    treats: ["Star-shaped shortbread", "Sparkleberry punch"],
    funFact: "Her flying ladder is named Larry and he giggles when he flies!",
    signOff: "Shine bright",
  },
  {
    id: "sugarplum",
    name: "Sugarplum",
    gender: "girl",
    emoji: "🧁",
    accent: "from-pink-400 to-fuchsia-600",
    bio: "Sugarplum runs the Sweet Shop and invents new candy flavors that taste like happiness.",
    personality: "Bubbly and generous",
    hobbies: ["Candy inventing", "Cupcake decorating", "Twirling"],
    job: "Sweet Shop Owner",
    treats: ["Sugarplum gumdrops", "Rainbow frosting cupcakes"],
    funFact: "She invented a lollipop that never gets smaller!",
    signOff: "Sweetness and sprinkles",
  },
  {
    id: "noelle",
    name: "Noelle",
    gender: "girl",
    emoji: "💌",
    accent: "from-red-500 to-pink-600",
    bio: "Noelle works in Santa's Mail Room reading letters from children all over the world.",
    personality: "Thoughtful and a great listener",
    hobbies: ["Letter writing", "Stamp collecting", "Storytelling"],
    job: "Santa's Mail Room Manager",
    treats: ["Envelope-shaped wafers", "Raspberry ribbon candy"],
    funFact: "She has read over one million letters to Santa!",
    signOff: "Sealed with Christmas magic",
  },
  {
    id: "crystal",
    name: "Crystal Frost",
    gender: "girl",
    emoji: "❄️",
    accent: "from-cyan-400 to-blue-600",
    bio: "Crystal designs every single snowflake that falls at the North Pole. No two are ever the same!",
    personality: "Creative and dreamy",
    hobbies: ["Snowflake designing", "Ice dancing", "Cloud watching"],
    job: "Snowflake Designer",
    treats: ["Snowflake sugar cookies", "Frozen berry slushies"],
    funFact: "She once made a snowflake shaped like a puppy!",
    signOff: "Flurries of fun",
  },
  {
    id: "ginger",
    name: "Ginger Snap",
    gender: "girl",
    emoji: "🏠",
    accent: "from-amber-500 to-orange-700",
    bio: "Ginger builds real gingerbread houses that elves actually live in — including her own!",
    personality: "Hardworking and hilarious",
    hobbies: ["Gingerbread architecture", "Icing art", "Gumdrop gardening"],
    job: "Gingerbread House Builder",
    treats: ["Fresh gingerbread", "Icing swirl cones"],
    funFact: "Her gingerbread house has a working candy doorbell!",
    signOff: "Snaps and smiles",
  },
  {
    id: "aurora",
    name: "Aurora",
    gender: "girl",
    emoji: "🌌",
    accent: "from-indigo-500 to-purple-700",
    bio: "Aurora paints the Northern Lights every night with her giant magical paintbrush.",
    personality: "Calm and magical",
    hobbies: ["Sky painting", "Star naming", "Midnight sleigh rides"],
    job: "Northern Lights Painter",
    treats: ["Galaxy swirl lollipops", "Moonbeam meringues"],
    funFact: "She lets baby polar bears pick the colors every Friday!",
    signOff: "Colors and constellations",
  },
  {
    id: "merry",
    name: "Merry Bright",
    gender: "girl",
    emoji: "💡",
    accent: "from-yellow-400 to-amber-500",
    bio: "Merry strings the twinkling lights across the whole North Pole village — millions of them!",
    personality: "Energetic and optimistic",
    hobbies: ["Light stringing", "Zip-lining between rooftops", "Giggling"],
    job: "Chief of Twinkling Lights",
    treats: ["Glow-berry tarts", "Lemon light drops"],
    funFact: "Her light displays can be seen from the moon (Santa checked)!",
    signOff: "Twinkle twinkle",
  },
  {
    id: "clara",
    name: "Clara Cuddles",
    gender: "girl",
    emoji: "🧸",
    accent: "from-rose-400 to-pink-600",
    bio: "Clara gives every teddy bear a hug before it goes in Santa's sack, so they arrive extra soft.",
    personality: "Gentle and loving",
    hobbies: ["Teddy bear hugging", "Blanket fort building", "Bedtime stories"],
    job: "Teddy Bear Quality Hugger",
    treats: ["Honey bear biscuits", "Warm milk with cinnamon"],
    funFact: "She has hugged 3,742,906 teddy bears (she keeps count)!",
    signOff: "Hugs and snuggles",
  },
  {
    id: "pippa",
    name: "Pippa Peppercorn",
    gender: "girl",
    emoji: "🎁",
    accent: "from-emerald-400 to-teal-600",
    bio: "Pippa is the fastest present wrapper in North Pole history — ribbons, bows, and all!",
    personality: "Speedy and giggly",
    hobbies: ["Present wrapping races", "Bow collecting", "Trampoline jumping"],
    job: "Head of the Wrapping Department",
    treats: ["Ribbon candy", "Present-shaped petit fours"],
    funFact: "She once wrapped a present while doing a cartwheel!",
    signOff: "Ribbons and bows",
  },
];
export function getElf(id: string): Elf {
  return ELVES.find((e) => e.id === id) ?? ELVES[0];
}
